<?php

namespace App\Http\Controllers\Kecamatan;

use App\Http\Controllers\Controller;
use App\Models\Umkm;
use App\Models\UmkmAdminLog;
use App\Models\Loker;
use App\Models\Desa;
use App\Models\PublicService;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class LayananPublikController extends Controller
{
    /**
     * --- UMKM RAKYAT FACILITATOR SECTION ---
     * Menggantikan fungsi UMKM lama dengan sistem UMKM Rakyat.
     */

    public function umkmIndex(Request $request)
    {
        $query = Umkm::latest();

        if ($request->has('q')) {
            $query->where('nama_usaha', 'like', '%' . $request->q . '%')
                ->orWhere('nama_pemilik', 'like', '%' . $request->q . '%');
        }

        $umkm = $query->paginate(10);
        return view('kecamatan.layanan.umkm.index', compact('umkm'));
    }

    public function umkmCreate(Request $request)
    {
        // Form "Bantu Daftarkan UMKM"
        $desas = Desa::orderBy('nama_desa')->get();

        // Auto-fill dari inbox (jika ada)
        $prefill = [
            'from_inbox' => $request->query('from_inbox'),
            'nama_pemilik' => $request->query('nama'),
            'no_wa' => $request->query('wa'),
            'desa' => $request->query('desa') ? Desa::find($request->query('desa'))?->nama_desa : null,
        ];

        return view('kecamatan.layanan.umkm.form_bantuan', compact('desas', 'prefill'));
    }

    public function umkmStore(Request $request)
    {
        $validated = $request->validate([
            'nama_usaha' => 'required|string|max:255',
            'nama_pemilik' => 'required|string|max:255',
            'no_wa' => 'required|string|max:20', // Format 62...
            'jenis_usaha' => 'required|string|max:100',
            'desa' => 'required|string',
            'notes' => 'nullable|string', // Catatan bantuan
        ]);

        // Create UMKM
        $umkm = new Umkm();
        $umkm->nama_usaha = $validated['nama_usaha'];
        $umkm->nama_pemilik = $validated['nama_pemilik'];
        $umkm->no_wa = $validated['no_wa'];
        $umkm->jenis_usaha = $validated['jenis_usaha'];
        $umkm->desa = $validated['desa'];

        // System fields
        $umkm->source = Umkm::SOURCE_ADMIN; // created_by kecamatan
        $umkm->status = Umkm::STATUS_AKTIF; // Langsung aktif agar bisa langsung dikelola, tapi butuh handover
        $umkm->ownership_status = 'pending_transfer'; // Menunggu warga ambil alih via link

        $umkm->save(); // Slug & Token generated by Model Boot

        // Log Action
        UmkmAdminLog::create([
            'umkm_id' => $umkm->id,
            'action' => 'create',
            'actor' => 'admin', // Kecamatan
            'notes' => 'Pendaftaran jalur bantuan (Fasilitator). ' . ($validated['notes'] ?? ''),
        ]);

        // Redirect to Handover Page
        return redirect()->route('kecamatan.umkm.handover', $umkm->id)
            ->with('success', 'UMKM berhasil didaftarkan. Segera lakukan serah terima digital.');
    }

    public function umkmHandover($id)
    {
        $umkm = Umkm::findOrFail($id);

        // Generate Link
        $manageLink = route('umkm_rakyat.manage', $umkm->manage_token);

        // WhatsApp Message generator
        $waMessage = "Halo {$umkm->nama_pemilik},\n\n";
        $waMessage .= "Berikut adalah link akses untuk mengelola Lapak UMKM Anda ({$umkm->nama_usaha}).\n\n";
        $waMessage .= "Silakan klik link ini untuk mulai melengkapi produk dan foto:\n";
        $waMessage .= $manageLink . "\n\n";
        $waMessage .= "Simpan link ini baik-baik. Jangan berikan kepada orang lain.";

        $waUrl = "https://wa.me/{$umkm->no_wa}?text=" . urlencode($waMessage);

        return view('kecamatan.layanan.umkm.handover', compact('umkm', 'manageLink', 'waUrl', 'waMessage'));
    }

    public function umkmEdit($id)
    {
        $umkm = Umkm::findOrFail($id);
        $desas = Desa::orderBy('nama_desa')->get();
        return view('kecamatan.layanan.umkm.edit_admin', compact('umkm', 'desas'));
    }

    public function umkmUpdate(Request $request, $id)
    {
        $umkm = Umkm::findOrFail($id);

        $validated = $request->validate([
            'nama_usaha' => 'required|string|max:255',
            'nama_pemilik' => 'required|string|max:255',
            'no_wa' => 'required|string|max:20',
            'jenis_usaha' => 'required|string',
            'desa' => 'required|string',
        ]);

        $umkm->update($validated);

        UmkmAdminLog::create([
            'umkm_id' => $umkm->id,
            'action' => 'verify',
            'actor' => 'admin',
            'notes' => 'Koreksi data administratif oleh kecamatan.',
        ]);

        return redirect()->route('kecamatan.umkm.index')->with('success', 'Data administratif UMKM diperbarui.');
    }

    public function umkmDestroy($id)
    {
        $umkm = Umkm::findOrFail($id);
        $umkm->delete();

        return redirect()->route('kecamatan.umkm.index')->with('success', 'UMKM dinonaktifkan/dihapus.');
    }

    public function resetAkses($id)
    {
        $umkm = Umkm::findOrFail($id);
        $umkm->manage_token = Str::random(40);
        $umkm->save();

        UmkmAdminLog::create([
            'umkm_id' => $umkm->id,
            'action' => 'activate',
            'actor' => 'admin',
            'notes' => 'Reset akses (Token baru) atas permintaan warga.',
        ]);

        return redirect()->route('kecamatan.umkm.handover', $umkm->id)
            ->with('success', 'Akses UMKM berhasil di-reset. Silakan berikan link baru.');
    }

    /**
     * --- LOKER WARGA SECTION ---
     * Mengelola papan informasi kerja informal warga.
     */
    public function lokerIndex(Request $request)
    {
        $query = Loker::with('desa')->latest();

        if ($request->has('q')) {
            $query->where(function ($q) use ($request) {
                $q->where('title', 'like', '%' . $request->q . '%')
                    ->orWhere('job_category', 'like', '%' . $request->q . '%')
                    ->orWhere('contact_wa', 'like', '%' . $request->q . '%');
            });
        }

        if ($request->has('status')) {
            $query->where('status', $request->status);
        }

        $loker = $query->paginate(15);
        return view('kecamatan.layanan.loker.index', compact('loker'));
    }

    public function lokerCreate(Request $request)
    {
        $desas = Desa::orderBy('nama_desa')->get();
        // Prefill from inbox if needed
        $prefill = [
            'from_inbox' => $request->query('from_inbox'),
            'title' => $request->query('title'),
            'wa' => $request->query('wa'),
            'desa_id' => $request->query('desa_id'),
        ];
        return view('kecamatan.layanan.loker.form', compact('desas', 'prefill'));
    }

    public function lokerStore(Request $request)
    {
        $validated = $request->validate([
            'title' => 'required|string|max:255',
            'job_category' => 'required|string',
            'contact_wa' => 'required|string|max:20',
            'desa_id' => 'nullable|exists:desa,id',
            'nama_desa_manual' => 'nullable|string|max:255',
            'description' => 'nullable|string',
            'work_time' => 'nullable|string',
            'status' => 'required|string',
            'is_sensitive' => 'nullable|boolean',
            'internal_notes' => 'nullable|string',
        ]);

        $validated['source'] = 'admin_input';
        $validated['is_available_today'] = $request->has('is_available_today');

        Loker::create($validated);

        return redirect()->route('kecamatan.loker.index')->with('success', 'Data Loker Warga berhasil ditambahkan.');
    }

    public function lokerEdit($id)
    {
        $loker = Loker::findOrFail($id);
        $desas = Desa::orderBy('nama_desa')->get();
        return view('kecamatan.layanan.loker.form', compact('loker', 'desas'));
    }

    public function lokerUpdate(Request $request, $id)
    {
        $loker = Loker::findOrFail($id);

        $validated = $request->validate([
            'title' => 'required|string|max:255',
            'job_category' => 'required|string',
            'contact_wa' => 'required|string|max:20',
            'desa_id' => 'nullable|exists:desa,id',
            'nama_desa_manual' => 'nullable|string|max:255',
            'description' => 'nullable|string',
            'work_time' => 'nullable|string',
            'status' => 'required|string',
            'is_sensitive' => 'nullable|boolean',
            'internal_notes' => 'nullable|string',
        ]);

        $validated['is_available_today'] = $request->has('is_available_today');

        $loker->update($validated);

        return redirect()->route('kecamatan.loker.index')->with('success', 'Data Loker Warga berhasil diperbarui.');
    }

    public function lokerDestroy($id)
    {
        $loker = Loker::findOrFail($id);
        $loker->delete();

        return redirect()->route('kecamatan.loker.index')->with('success', 'Data Loker Warga berhasil dihapus.');
    }
}
