version: '3.8'

services:
  traefik:
    image: traefik:v3.1
    container_name: traefik-gateway
    restart: unless-stopped
    user: "0:1001"
    networks:
      - kecamatan-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme.json:/acme.json
      - ./dynamic_conf.yml:/dynamic_conf.yml:ro
    environment:
      - TZ=Asia/Jakarta
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.file.filename=/dynamic_conf.yml"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.email=admin@kecamatanbesuk.my.id"
      - "--certificatesresolvers.myresolver.acme.storage=acme.json"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--log.level=INFO"

networks:
  kecamatan-network:
    external: true
